<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\DirectoryService.Infrastructure\DirectoryService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\DirectoryService.Presentation\appsettings.json"
             Link="appsettings.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
